### ISSUE TITLE
[ERROR] Cannot start nuxt:  Cannot find module

### ISSUE THREAD

**Issue by MohmmedAshraf** [fumeapp/tailvue#1]
Hi, I have a fresh nuxt3 install when trying to install tailvue, I got this error even on Stackblitz

Stackblitz: https://stackblitz.com/edit/github-8amzbs?file=nuxt.config.ts

```
 ERROR  Cannot start nuxt:  Cannot find module '/home/projects/github-8amzbs/node_modules/@tailvue/nuxt/dist/module.cjs'                                      15:42:23

  at createEsmNotFoundErr (https://github-8amzbs.w.staticblitz.com/blitz.bc2b78560fa0e6097e7f69d4e820659cab64d2c5.js:6:163045)
  at finalizeEsmResolution (https://github-8amzbs.w.staticblitz.com/blitz.bc2b78560fa0e6097e7f69d4e820659cab64d2c5.js:6:162950)
  at resolveExports (https://github-8amzbs.w.staticblitz.com/blitz.bc2b78560fa0e6097e7f69d4e820659cab64d2c5.js:6:160058)
  at Function.Module._findPath (https://github-8amzbs.w.staticblitz.com/blitz.bc2b78560fa0e6097e7f69d4e820659cab64d2c5.js:6:160592)
  at Function.Module._resolveFilename (https://github-8amzbs.w.staticblitz.com/blitz.bc2b78560fa0e6097e7f69d4e820659cab64d2c5.js:6:165652)
  at Function.resolve (https://github-8amzbs.w.staticblitz.com/blitz.bc2b78560fa0e6097e7f69d4e820659cab64d2c5.js:6:427541)
  at Function.p [as resolve] (node_modules/jiti/dist/jiti.js:1:53000)
  at resolveModule (node_modules/@nuxt/kit/dist/index.mjs:123:36)
  at Module.installModule (node_modules/@nuxt/kit/dist/index.mjs:1286:18)
  at initNuxt (node_modules/nuxt3/dist/index.mjs:893:21)

```

Thanks

**Comment by acidjazz** [comment]
Thanks for reporting this @MohmmedAshraf  - looks like this is our culprit: https://github.com/egoist/rollup-plugin-esbuild/issues/325

**Comment by acidjazz** [comment]
@MohmmedAshraf until i get this issue fixed, feel free to install https://github.com/fumeapp/tailvue/releases/tag/v0.1.52 until then.

**Comment by MohmmedAshraf** [comment]
@acidjazz previous version works fine, thank you

**Comment by eyopa21** [comment]
> Hi, I have a fresh nuxt3 install when trying to install tailvue, I got this error even on Stackblitz
> 
> Stackblitz: https://stackblitz.com/edit/github-8amzbs?file=nuxt.config.ts
> 
> ```
>  ERROR  Cannot start nuxt:  Cannot find module '/home/projects/github-8amzbs/node_modules/@tailvue/nuxt/dist/module.cjs'                                      15:42:23
> 
>   at createEsmNotFoundErr (https://github-8amzbs.w.staticblitz.com/blitz.bc2b78560fa0e6097e7f69d4e820659cab64d2c5.js:6:163045)
>   at finalizeEsmResolution (https://github-8amzbs.w.staticblitz.com/blitz.bc2b78560fa0e6097e7f69d4e820659cab64d2c5.js:6:162950)
>   at resolveExports (https://github-8amzbs.w.staticblitz.com/blitz.bc2b78560fa0e6097e7f69d4e820659cab64d2c5.js:6:160058)
>   at Function.Module._findPath (https://github-8amzbs.w.staticblitz.com/blitz.bc2b78560fa0e6097e7f69d4e820659cab64d2c5.js:6:160592)
>   at Function.Module._resolveFilename (https://github-8amzbs.w.staticblitz.com/blitz.bc2b78560fa0e6097e7f69d4e820659cab64d2c5.js:6:165652)
>   at Function.resolve (https://github-8amzbs.w.staticblitz.com/blitz.bc2b78560fa0e6097e7f69d4e820659cab64d2c5.js:6:427541)
>   at Function.p [as resolve] (node_modules/jiti/dist/jiti.js:1:53000)
>   at resolveModule (node_modules/@nuxt/kit/dist/index.mjs:123:36)
>   at Module.installModule (node_modules/@nuxt/kit/dist/index.mjs:1286:18)
>   at initNuxt (node_modules/nuxt3/dist/index.mjs:893:21)
> ```
> 
> Thanks

Use  **@tailvue/nuxt** instead, 
yarn add --dev @tailvue/nuxt
