### ISSUE TITLE
[ERROR] Document is not defined

### ISSUE THREAD

**Issue by ridopurnomo86** [fumeapp/tailvue#24]
i have some trouble use tailvue inside serverSide ?
but work if i wrap "<ClientOnly>"

can i use tailvue with serverSide ?
any ideas ?

document is not defined

at setup (C:\Users\ridop\Documents\Personal\fews-frontend\views\auth\Signup\Form\index.js:27:42)
at _sfc_main.setup (C:\Users\ridop\Documents\Personal\fews-frontend\views\auth\Signup\Form\index.js:252:23)
at callWithErrorHandling (C:\Users\ridop\Documents\Personal\fews-frontend\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:171:22)
at setupStatefulComponent (C:\Users\ridop\Documents\Personal\fews-frontend\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:7194:29)
at setupComponent (C:\Users\ridop\Documents\Personal\fews-frontend\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:7149:11)
at renderComponentVNode (C:\Users\ridop\Documents\Personal\fews-frontend\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:628:17)
at renderVNode (C:\Users\ridop\Documents\Personal\fews-frontend\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:755:22)
at renderVNodeChildren (C:\Users\ridop\Documents\Personal\fews-frontend\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:770:9)
at renderElementVNode (C:\Users\ridop\Documents\Personal\fews-frontend\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:821:17)

**Comment by acidjazz** [comment]
I don't think you'd want to try and use it server-side - it's trying to bind elements to the DOM (hence document) - there is no DOM when you're SSR in NuxtJS

**Comment by ridopurnomo86** [comment]
> I don't think you'd want to try and use it server-side - it's trying to bind elements to the DOM (hence document) - there is no DOM when you're SSR in NuxtJS

i mean it only work if i wrap <ClientOnly></ClientOnly>

**Comment by ridopurnomo86** [comment]
> I don't think you'd want to try and use it server-side - it's trying to bind elements to the DOM (hence document) - there is no DOM when you're SSR in NuxtJS

so helpfull, thank you
